### ISSUE TITLE
Question: Will there be any race conditions when CNI plugin is invoked in a multi-thread way?

### ISSUE THREAD

**Issue by qianzhangxa** [appc/cni#118]
Hi,

I'd like to know if there will be any race conditions when CNI plugin is invoked in a multi-thread way, e.g., `host-local` ipam plugin is used and the subnet is `10.0.0.0/24`, now there is already an IP `10.0.0.2` allocated and this ipam plugin is called by two threads simultaneously, will both of these two calls see `10.0.0.3` is free to use and assign it to two containers? Or there is a mechanism to ensure one container gets `10.0.0.3` and the other container gets `10.0.0.4`?

**Comment by dcbw** [comment]
The host-local backend store uses OS-level file locks to ensure exclusive access to the address database.  So concurrent calls to the host-local IPAM plugin should not result in duplicate address allocation as long as the filesystem correctly implements flock.

**Comment by qianzhangxa** [comment]
Got it, thanks @dcbw !
