### ISSUE TITLE
flannel: Why does flannel call ipam.ExecAdd() to invoke delegated plugin

### ISSUE THREAD

**Issue by qianzhangxa** [appc/cni#123]
In the `delegateAdd()` of flannel plugin (https://github.com/appc/cni/blob/master/plugins/meta/flannel/flannel.go#L158), I see `ipam.ExecAdd()` is called to invoke the delegated plugin (e.g., bridge), it looks a little strange to me that a IPAM method is called to invoke a main plugin, Why not directly call `invoke.ExecPluginWithResult()` to invoke the main plugin?

**Comment by steveeJ** [comment]
@squaremo can you jump in here? Github told me you wrote the line in question :-)

**Comment by squaremo** [comment]
Ahhh yes, I think I know this one -- the Exec* procedures originally lived in the `ipam` package. I factored them out so they could be used by libcni, leaving shims behind for convenience -- and apparently neglected to update this use. I'll correct it.
