### ISSUE TITLE
Question: How to get both IPv4 and IPv6 address from a network

### ISSUE THREAD

**Issue by qianzhangxa** [appc/cni#124]
In https://github.com/appc/cni/blob/master/SPEC.md, I see a sentence: 
`IPs assigned to the interface. This is either an IPv4 address, an IPv6 address, or both.`
So does that mean I can get both IPv4 and IPv6 address from a single network? If yes, I'd like to know what kind of network configuration can support such use case? I thought in the "ipam" section of a network configuration, there can only be one subnet which should be either IPv4 or IPv6 but not both.

**Comment by steveeJ** [comment]
Strictly seen the IPAM section doesn't directly configure the IP range. It covers _type_ and _routes_ as described in the [SPEC.md#network-configuration](https://github.com/appc/cni/blob/master/SPEC.md#network-configuration). The IP specific parameters belong to the _host-local_ IPAM plugin which allows you to specify either IPv4 or IPv6 information. _dhcp_ would be an example that could return both address types but that has not yet been implemented.

**Comment by qianzhangxa** [comment]
Thanks @steveeJ, so for *host-local* IPAM plugin, I can only specify either IPv4 and IPv6 range but not both, and we do not have plan to let it support both in future, right?

**Comment by steveeJ** [comment]
@qianzhangxa we do have plans to support both with host-local in the future. I'm currently working on a proposal to make the model more flexible.

**Comment by qianzhangxa** [comment]
Great to know, thanks @steveeJ !

**Comment by steveeJ** [comment]
Closing in favor of #131.
