### ISSUE TITLE
Question: Is there a plan to support port forwarding in CNI

### ISSUE THREAD

**Issue by qianzhangxa** [appc/cni#139]
Hi,

I'd like to know if there is a plan to support port forwarding (e.g., forward the packet sent to a host port to a container port) in CNI plugin (e.g., bridge plugin). I think this is a common and useful feature, thanks!

**Comment by steveeJ** [comment]
Port forwarding is currently beyond the scope of CNI and there is currently no plans to change that. However if you have a good use-case please provide a thorough explanation and at best paired with a pull-request ;-)

**Comment by steveeJ** [comment]
Closing in favor of #46
