### ISSUE TITLE
Investigate ipMasq support from macvlan and ipvlan

### ISSUE THREAD

**Issue by eyakubovich** [appc/cni#14]
I don't think it's really possible to get IP masquerade to work with macvlan as it operates at L2 and probably does not call into netfilter code. In that case, support for it should be removed. ipvlan maybe can work (maybe in one of the modes) but needs to be investigated.

**Comment by steveeJ** [comment]
This can't work for any of macvlan and ipvlan, because they're traffic is passed through the host interface without being able to talk to it. The only way of having ipMasq for these plugins is to have an additional network in the netns.
