### ISSUE TITLE
[Question] How is veth deleted in the host with bridge plugin?

### ISSUE THREAD

**Issue by qianzhangxa** [appc/cni#152]
Hi,

For the bridge plugin, in its `cmdDel()` method, I only see the interface of the container (e.g., eth0) will be deleted:
https://github.com/appc/cni/blob/master/plugins/main/bridge/bridge.go#L244:L246

But how about the other end of the pair in the host (e.g., vethxxx)? I do not see the code to delete it, but the fact is it is indeed deleted. Is it because it will be automatically deleted after the container inferface is deleted?

**Comment by zachgersh** [comment]
Hey @qianzhangxa - you are exactly right!

**Comment by qianzhangxa** [comment]
Got it, thanks @zachgersh !
