### ISSUE TITLE
please tag new release

### ISSUE THREAD

**Issue by onlyjob** [appc/cni#166]
Please tag new formal release.
Kubernetes v1.2.0 already vendored unreleased (post 0.1.0) snapshot of _appc/cni_. :(

**Comment by jonboulle** [comment]
This will happen for 0.2.0 imminently, and we plan to be more diligent about releases going forward.

**Comment by onlyjob** [comment]
Thanks.

**Comment by alban** [comment]
CNI also vendor dependencies and some of them are not a release, e.g. CNI depends on coreos/go-systemd commit https://github.com/coreos/go-systemd/commit/2688e91251d9d8e404e86dd8f096e23b2f086958 instead of a tag. Should they be updated too?

**Comment by onlyjob** [comment]
Yes please, that would be beneficial and useful. Ideally all (vendored) dependencies should be tag-based, whenever possible. 

Contrary to random unreleased snapshot, tagged/versioned dependencies can provide certain benefits of stability and notion of production readiness.

Versioning provides safety margin for situations like "ops, we've made a mistake but corrected problematic commit in master". Presumably tagged version/release is better tested/reviewed than random snapshot of "master" branch. Especially for [semantically versioned](http://semver.org/) libraries.

I hope that makes sense.

**Comment by zachgersh** [comment]
@jonboulle / @onlyjob may be beneficial to just tag now (nothing to crazy) and then move most of our work over to another branch called "develop". I've seen that pattern a bunch.

**Comment by jonboulle** [comment]
Yeah, I've used that pattern a bunch, but I don't think it buys much :-). IMHO let's just stick to master + tags, until there's a clear need for something more complicated.

**Comment by zachgersh** [comment]
@jonboulle sounds good. Closing.

**Comment by onlyjob** [comment]
Sorry for pedantic note but maybe we close this bug _after_ new release is tagged?

**Comment by jonboulle** [comment]
I agree :P

**Comment by steveeJ** [comment]
https://github.com/appc/cni/releases/tag/v0.2.0-rc0

**Comment by onlyjob** [comment]
Stanks, @steveeJ. :) Please remember to tag release as soon as it is ready. :)
