### ISSUE TITLE
bridge cni plugin creates containers with no connectivity due to bad arp table

### ISSUE THREAD

**Issue by mikedanese** [appc/cni#191]
I'm using the kubenet plugin for kubelet which is creating docker containers with the cni config:
```json
{
  "cniVersion": "0.1.0",
  "name": "kubenet",
  "type": "bridge",
  "bridge": "cbr0",
  "mtu": 1460,
  "addIf": "eth0",
  "isGateway": true,
  "ipMasq": true,
  "ipam": {
    "type": "host-local",
    "subnet": "10.244.1.0/24",
    "gateway": "10.244.1.1",
    "routes": [
      { "dst": "0.0.0.0/0" }
    ]
  }
}
```

The containers create, but the container IPs are unreachable from the host and there's no connectivity from inside the container to outside. Further debugging leads to this:

```console
root@k-0-minion-4c6o:~# ip neigh
10.128.0.1 dev ens4 lladdr 42:01:0a:80:00:01 REACHABLE
10.244.1.3 dev cbr0  FAILED
10.244.1.5 dev cbr0  FAILED
172.17.0.2 dev docker0 lladdr 02:42:ac:11:00:02 STALE
root@k-0-minion-4c6o:/# ip route
default via 10.128.0.1 dev ens4 
10.128.0.1 dev ens4  scope link 
10.244.1.0/24 dev cbr0  proto kernel  scope link  src 10.244.1.1 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
root@k-0-minion-4c6o:~# arp
Address                  HWtype  HWaddress           Flags Mask            Iface
10.128.0.1               ether   42:01:0a:80:00:01   C                     ens4
10.244.1.3                       (incomplete)                              cbr0
10.244.1.5                       (incomplete)                              cbr0
172.17.0.2               ether   02:42:ac:11:00:02   C                     docker0
```

I'm happy to provide further debugging info but I'm looking for a lead on what to checkout next.

cc @freehan

**Comment by bprashanth** [comment]
@dcbw

**Comment by steveeJ** [comment]
The first but probably unrelated thing to note is that `  "addIf": "eth0",` from the configuration is not supported by the bridge plugin that lives in this repository, although it has been raised in #40.

For debugging these things would be useful:
* {ip,eb,arp}tables rules
* `ip a`

**Comment by mikedanese** [comment]
Thanks for the help! I think i've figured it out. It turns out it was related to the tc config applied by kubelet and is not an issue with cni.

**Comment by colinmorelli** [comment]
@mikedanese Do you have any more info on this? Running into what appears to be the same issue.

**Comment by mikedanese** [comment]
@colinmorelli because golang defaults ints to 0, not providing a qlen (queue length) to cni caused the qlen to cni when creating a bridge defaulted to building a bridge with qlen 0. This is totally fine until you apply qdisc (queue disciplines) other than noqueue. In my case I was applying htb. This was fixed by instead passing -1 for qlen to the NF_SOCKET when creating the bridge, which tells the kernel to use the default of 1000. 

@dcbw was the one who figured this out.

**Comment by mikedanese** [comment]
Easy way to check: look at the qlen and and the qdisc on your bridge.

**Comment by colinmorelli** [comment]
Unfortunately that does not seem to be my issue. But, thanks for the speedy reply!

**Comment by zhqqqy** [comment]
@mikedanese I think I have encountered the same problem as you. How did you finally add qlen's configuration? I can't access any network after setting `tc qdisc add dev eth0 handle 10: root htb default 1`

**Comment by zhqqqy** [comment]
I know, use this command  to set qlen `ip link set txqueuelen 500 dev eth0`
