### ISSUE TITLE
host-local should use /run and not /var for persistance

### ISSUE THREAD

**Issue by eyakubovich** [appc/cni#26]
There's no reason for the IP assignments on the host to survive a reboot.

**Comment by eyakubovich** [comment]
That is not actually obvious. Since (exited) containers might survive reboots, losing the IP <--> ContainerID mapping will cause the DEL command to fail.

**Comment by jonboulle** [comment]
So what's the plan?

**Comment by eyakubovich** [comment]
Keeping as is.
