### ISSUE TITLE
meet error in ubuntu system when build cni

### ISSUE THREAD

**Issue by zenlinTechnofreak** [appc/cni#28]
When I run build, it will meet the error as log in the screen catch as below.

![cni build screen cut](https://cloud.githubusercontent.com/assets/9923237/8521433/137cb1a2-2416-11e5-927e-238d3062879a.png)

my environment:
Linux zenlin-pc 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Can anyone help me to fix it, or tell me to how to fix it ,I just want to use the cni, and I am going to contribute to it.THX.

**Comment by zenlinTechnofreak** [comment]
@eyakubovich @jonboulle @steveeJ, plz help me, thanks very much

**Comment by zenlinTechnofreak** [comment]
@eyakubovich @jonboulle @steveeJ,  I was waiting on the line, is it means  the cni only support the coreos or solaris yet, but not others?

**Comment by jonboulle** [comment]
@zenlinTechnofreak We have a requirement on go 1.4+ and it looks like you're using <=1.3. Can you try with a newer version and we can take it from there?

**Comment by eyakubovich** [comment]
@zenlinTechnofreak @jonboulle is correct, Unsetenv was added in Go 1.4.

**Comment by zenlinTechnofreak** [comment]
OK, I am trying to update the go version, plz hold on ,  I will get the response to u. thanks for your help.

**Comment by zenlinTechnofreak** [comment]
@eyakubovich @jonboulle , I have changed the go to go 1.4 version, but the err is also the same as before.
![cni build](https://cloud.githubusercontent.com/assets/9923237/8537488/1b9a67f4-2492-11e5-980f-c458750d28fb.png)

**Comment by zenlinTechnofreak** [comment]
when I run the build command with root user, we can see that  many errs,

such as,
root@zenlin-pc:/home/zenlin/workspace/cni# ./build 
Building plugins
   flannel
gopath/src/github.com/appc/cni/plugins/meta/flannel/flannel.go:22:2: cannot find package "bufio" in any of:
	/home/zenlin/go/src/pkg/bufio (from $GOROOT)
	/home/zenlin/workspace/cni/gopath/src/bufio (from $GOPATH)
	/home/zenlin/workspace/cni/Godeps/_workspace/src/bufio
gopath/src/github.com/appc/cni/pkg/plugin/ipam.go:18:2: cannot find package "bytes" in any of:
	/home/zenlin/go/src/pkg/bytes (from $GOROOT)
	/home/zenlin/workspace/cni/gopath/src/bytes (from $GOPATH)
	/home/zenlin/workspace/cni/Godeps/_workspace/src/bytes'

It seems that the plugins find the wrong way to read go lib, but my go path and go root is set correctly,
as below,
root@zenlin-pc:/home/zenlin/go/pkg# echo $GOPATH
/home/zenlin/workspace/go
root@zenlin-pc:/home/zenlin/go/pkg# echo $GOROOT
/home/zenlin/go

**Comment by zenlinTechnofreak** [comment]
@jonboulle @eyakubovich  I am sorry that I have fixed out the problem, there are some err with my path config with go env, now, correctly runing, also, thx for your help,  the issue first caused by the low version golang, and second issue cased by the worng config for go, I want to add the remind for user in readme doc, do u agree with me?

**Comment by jonboulle** [comment]
Thanks, glad you got it sorted. Let's follow up in #30
