### ISSUE TITLE
Investigate using p-t-p device for "ptp" plugin

### ISSUE THREAD

**Issue by eyakubovich** [appc/cni#38]
The old p-t-p dialup links were set up so that all interfaces had the same IP on the server. I think we can use the same idea here. This should allow us to use only one IP per container in the case of "ptp" plugin.

**Comment by steveeJ** [comment]
@eyakubovich This is somewhat deprecated by #63, or do you see any follow-up work left?

**Comment by eyakubovich** [comment]
Implemented (to the best it's possible) by #63
