### ISSUE TITLE
When does CNI_COMMAND equal DEL?

### ISSUE THREAD

**Issue by rushmorem** [appc/cni#48]
I have a bash prototype plugin with two functions `activate_network` (for when the container starts) and `deactivate_network` for when then container exits. My environment is as follows:-
```
rkt version 0.8.0
appc version 0.6.1
```
and I have the following block at the end of the plugin:-
```bash
if [[ "${CNI_COMMAND}" == "ADD" ]]; then
        activate_network
elif [[ "${CNI_COMMAND}" == "DEL" ]]; then
        deactivate_network
fi
```

When the container starts, `$CNI_COMMAND` is equal to `ADD` so networking is setup fine. However on exit, `deactivate_network` is never run. Am I missing something?

**Comment by jonboulle** [comment]
Have you tried running `rkt gc`? I believe it will only be called at that stage?

**Comment by rushmorem** [comment]
@jonboulle Yes I did (`rkt gc --grace-period=0s`). Unfortunately `deactivate_network` doesn't seem to be getting called then either.

**Comment by steveeJ** [comment]
@rushmorem: I just used one of your pasted bash scripts as a plugin and can confirm that `DEL` works for me when I do a `rkt run` followed by a `rkt gc --grace-period=0s`.
I added this to the script
```
echo --- >> /tmp/dump.txt                                                                                            
echo $(env | grep CNI) >> /tmp/dump.txt                                                                              
echo --- >> /tmp/dump.txt 
```

And can see the following lines in the file:
```
---
CNI_ARGS= CNI_COMMAND=DEL CNI_IFNAME=eth0 CNI_NETNS=netns CNI_CONTAINERID=e624be83-d505-4b63-a73f-b8d17223c18d CNI_PATH=/usr/lib/rkt/plugins/net:stage1/rootfs/usr/lib/rkt/plugins/net
---
---
CNI_ARGS= CNI_COMMAND=DEL CNI_IFNAME=eth0 CNI_NETNS=netns CNI_CONTAINERID=fe103d5d-c7f3-45d2-ae51-265848c9aa1c CNI_PATH=/usr/lib/rkt/plugins/net:stage1/rootfs/usr/lib/rkt/plugins/net
---
```

Please investigate your setup again since it should really work for you too. If you still encounter this problem I would like you to file an issue against rkt because it's the active component in the garbage collection scenario.

**Comment by rushmorem** [comment]
Thanks @steveeJ. I must be doing something wrong. Will try again later.

**Comment by steveeJ** [comment]
@rushmorem Can we close this or do you have any other questions about the matter?

**Comment by rushmorem** [comment]
@steveeJ sorry I haven't had time to test this yet but I suppose we can close it.
