### ISSUE TITLE
Loopback devices - UP by default on host-bridge?

### ISSUE THREAD

**Issue by zachgersh** [appc/cni#97]
Hey All,

On the host-bridge plugin the loopback device is down by default. Is there any particular reason for that or could we set it to up as part of the plugin itself? Maybe we introduce a conf value to handle whether or not to up the loopback device in the namespace?

**Comment by steveeJ** [comment]
The [README](https://github.com/appc/cni/blob/6fc3874d57164f7794c4265005200028b7b5e47e/README.md#running-the-plugins) shows an example for the bridge plugin and it clearly states the loopback device as UP.

Please describe your steps so we have a chance to reproduce your situation and find a solution.

**Comment by sykesm** [comment]
@steveeJ the `priv-net-run.sh` script is actually [bringing the link up][up]. I think @zachgersh was trying to imply that the action should be part of the host-bridge plugin?

[up]: https://github.com/appc/cni/blob/master/scripts/priv-net-run.sh#L9

**Comment by zachgersh** [comment]
@steveeJ, @sykesm is totally correct. I don't believe this should be logic that is housed in a .sh file and should instead be part of the plugins responsibility.

**Comment by steveeJ** [comment]
I see, and totally agreed. I'm also wondering why it's not part of the plugin, and I don't see a reason to keep it like this.

@sykesm @zachgersh  Is one of you volunteering for this one? :-)

**Comment by zachgersh** [comment]
@steveeJ I will take this :+1:

**Comment by rosenhouse** [comment]
an alternative could be a dedicated plugin called "loopback" that just up's it and sets the addresses to 127.0.0.1 and ::1 (h/t to @sykesm for the idea).

**Comment by steveeJ** [comment]
> an alternative could be a dedicated plugin called "loopback" that just up's it and sets the addresses to 127.0.0.1 and ::1 (h/t to @sykesm for the idea).

+1

**Comment by steveeJ** [comment]
With #121 merged it's pretty convenient for consumers to up the loopback device. 

@zachgersh are you OK with the solution or would you still like to make it the default behavior? I'll leaving closing of this issue to you.

**Comment by zachgersh** [comment]
Now that this is merged and the documentation is updated - this can totally be closed.
